add svg sprites
js-tasks-ru/htmlcss-20220414_elizaveta3 pull request #17
Opened 2022-05-05 20:39 UTC by LisaB1994

2022-05-05 20:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-06 12:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-10 19:24 UTC, GSemikozov requested changes

2022-05-10 19:24 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.icon-arrow {
.accordion__icon-arrow

2022-05-10 19:24 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details[open] .icon-arrow{
и тут. 
"залазить" в стили одних компонентов из других нельзя, только через классы-миксы если нужно примиксовать какие-то свойства (марджины и пр)

2022-05-10 19:24 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.icon-question{
.tooltip__icon

2022-05-10 19:24 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__icon{
оглядываясь назад - проще было бы создать отдельный блок .icon и ему задать ширину и высоту. А вот уже стили которые касаются внешнего позиционирования - через такого рода классы которые можно домиксовать к .icon

2022-05-11 10:45 UTC, LisaB1994 commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details[open] .icon-arrow{
вот тут не понимаю тогда как сделать.. 
я же обращаюсь иконке и говорю, если аккардион открыт, то сделай иконку такой то..

2022-05-11 10:56 UTC, LisaB1994 commented on 05-lection3/02-modal/modal.css
> +.modal__icon{
создала отдельный компонент icon и этому блоку задала размеры.

2022-05-11 19:11 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__details[open] .icon-arrow{
все верно, просто нужно через класс-микс - .accordion__icon например

2022-05-11 19:12 UTC, GSemikozov approved these changes

2022-05-11 19:12 UTC, merged