add checkbox
js-tasks-ru/htmlcss-20220414_elizaveta3 pull request #18
Opened 2022-05-08 15:09 UTC by LisaB1994

2022-05-08 15:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-08 15:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-10 19:26 UTC, GSemikozov requested changes

2022-05-10 19:26 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +    margin-right: 12px;
лучше указать на .checkbox__title поскольку тайтл - опциональный элемиент

2022-05-11 12:22 UTC, LisaB1994 commented on 07-lection5/01-checkbox/checkbox.css
> +    margin-right: 12px;
перенесла марджин на .checkbox__title

2022-05-11 19:13 UTC, GSemikozov approved these changes

2022-05-11 19:13 UTC, merged