add homework-skeleton
js-tasks-ru/htmlcss-20220414_elizaveta3 pull request #7
Opened 2022-04-26 12:43 UTC by LisaB1994

2022-04-26 12:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-27 08:44 UTC, GSemikozov requested changes

2022-04-27 08:44 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_first_full_width{
.skeleton__row_small

2022-04-27 08:44 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
здесь и ниже у подобных модификаторов ширину лучше задать в процентах

2022-04-27 08:44 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_second_full_width{
.skeleton__row_medium

2022-04-27 08:44 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_third_full_width{
.skeleton__row_full_width

2022-04-27 08:44 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_fourth_full_width{
.skeleton__row_large

2022-04-27 08:44 UTC, GSemikozov commented on assets/css/main.css
> +    --grey-skeleton: linear-gradient(92.51deg, #DDE2E5 6.44%, #E2E6E8 38.47%, #F3F5F5 56.48%, #E3E7EA 77.5%, #DDE2E5 102.52%);
--gradient

2022-04-27 14:58 UTC, LisaB1994 commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
задала родительским блокам ширину и самим строкам ширину в %, но почему то круг начало плющить..

2022-04-27 19:04 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
а если кругу задать flex-shrink: 1 или min-width: 64px?

2022-04-27 19:04 UTC, GSemikozov requested changes

2022-04-27 19:04 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 475px;
лишнее, удалим

2022-04-27 19:04 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 515px;
лишнее, удалим

2022-04-28 10:37 UTC, LisaB1994 commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
flex-shrink: 1; не помогло, это же значение по умолчанию. 
помогло flex-shrink: 0; и помогло min-width: 64px.
я оставила min-width: 64px.
спасибо!)

2022-04-30 16:58 UTC, GSemikozov approved these changes

2022-04-30 16:58 UTC, merged